-- AlterTable
ALTER TABLE `voucher` ADD COLUMN `max_usage` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maximum_price` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `minimum_price` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `voucher_end` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
